include $(TOPDIR)/rules.mk
LUCI_TITLE:=LuCI support for 9Router
LUCI_DEPENDS:=+9router +luci-base
PKG_NAME:=luci-app-9router
PKG_VERSION:=1.0
PKG_RELEASE:=1
include ../../luci.mk
# call BuildPackage - OpenWrt luci.mk handles it
